#ifndef _OBJECTTYPE_H_
#define _OBJECTTYPE_H_

enum RogueObjectType
{
	DEFAULT = 0,
	PLAYER_START = 1,
	PLAYER_RESTART = 2,
	TIE_FIGHTER = 12,
	GUN_TURRET = 13,
	PROBE_DROID = 14,
	ATAT_TYPE = 15,
	TIE_INTER = 18,
	TIE_BOMBER = 19,
	GENERIC_DESTROYABLE = 20,
	ATST_TYPE = 31,
	SHUTTLE = 36,
	TANKBOT = 37,
	CAMERA = 38,
	WINGMAN = 39,
	MEGA_TURRET = 40,
	TIE_D = 41,
	REB_TRANS = 43,
	CARGO = 45,
	REB_COMBAT = 46,
	STORMTROOPER = 59,
	REB_PILOT = 60,
	CIVILIAN = 61,
	ATTACK_CRAFT = 64,
	V_TCC_HI = 67, //???
	NON_DESTRUCTIBLE = 75,
	IBU_WE = 80 //???
};

#endif